In [3]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")

print(f"El archivo tiene {df.shape[0]} filas y {df.shape[1]} columnas.")

df.head(3)

El archivo tiene 8807 filas y 12 columnas.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [4]:
valores_nulos = df.isnull().sum()

print(valores_nulos)

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df["director"] = df["director"].fillna("Director desconocido")
df["cast"] = df["cast"].fillna("Elenco no disponible")
df["country"] = df["country"].fillna("Pais no especificado")

print(df.isnull().sum())

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [10]:
df = df.dropna(subset=["date_added", "rating", "duration"])

df = df.drop(columns=["show_id", "description"])

print(df.isnull().sum())
print(f"\nTamaño actual del set de datos: {df.shape}")

KeyError: "['show_id', 'description'] not found in axis"

In [12]:
df["release_year"] = df["release_year"].astype(int)

print(df["release_year"].head(3))

0    2020
1    2021
2    2021
Name: release_year, dtype: int64

In [13]:
df["genero_principal"] = df["listed_in"].str.split(",").str[0]

df[["listed_in","genero_principal"]].head(5)

                                           listed_in        genero_principal
0                                      Documentaries           Documentaries
1    International TV Shows, TV Dramas, TV Mysteries  International TV Shows
2  Crime TV Shows, International TV Shows, TV Act...          Crime TV Shows
3                             Docuseries, Reality TV              Docuseries
4  International TV Shows, Romantic TV Shows, TV ...  International TV Shows

In [14]:
df.to_csv("netflix_titles_limpio.csv", index=False)
print("Archivo guardado con exito")

Archivo guardado con exito